apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elk  # use your namespace
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    xpack.security.enabled: false
    xpack.ssl.enabled: false
