apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elk
data:
  filebeat.yml: |
    # Filebeat Configuration for Kubernetes
    filebeat.inputs:
      - type: container
        paths:
          - /var/lib/docker/containers/*/*.log
        processors:
          - add_docker_metadata: ~

    setup.kibana.host: "kibana:5601"  # Kibana service URL in Kubernetes (update if different)

    output.logstash:
      hosts: ["logstash:5044"]  # Logstash service URL (make sure Logstash is running and accessible)

    # Enable the Filebeat modules you need (for example, system, docker, etc.)
    # To enable specific modules, you can uncomment and configure them as needed.
    # filebeat.modules:
    #   - module: system
    #     syslog:
    #       enabled: true
    #     auth:
    #       enabled: true

    # Optional: Configure logging settings
    logging:
      level: info
      to_files: true
      files:
        path: /var/log/filebeat
        name: filebeat
        keepfiles: 7
        permissions: 0644
